// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialNetwork.Data;

namespace SocialNetwork.Migrations.FriendDb
{
    [DbContext(typeof(FriendDbContext))]
    partial class FriendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SocialNetwork.Accounts.Freinds.Friend", b =>
                {
                    b.Property<long>("FriendAccount")
                        .HasColumnType("bigint");

                    b.Property<long>("MyAccount")
                        .HasColumnType("bigint");

                    b.ToTable("FriendDb");
                });
#pragma warning restore 612, 618
        }
    }
}
